(* Linearly scans OCaml source code generated by a prepocessor for code sandwiched between line directives *)
{
  open Utils

  type result = {
    src_line : int;
    impl_line : int;
    range : Lexing.position * Lexing.position;
    text : string;
  }

  (* ---------------------------------------------------------- Object to buffer
     string literals, comments and actions. Adapted from
     ocamlformat.0.28.1/vendor/parser-extended/lexer.mll *)

  class lexeme_buffer =
    object (self)
      val string_buffer = Buffer.create 256

      (* To store the position of the beginning of a string and comment *)
      val string_start_loc = ref Lexing.dummy_pos

      method set_start_loc lexbuf =
        string_start_loc := Lexing.lexeme_start_p lexbuf

      method reset_string_buffer () = Buffer.reset string_buffer
      method get_stored_string () = Buffer.contents string_buffer
      method store_string_char c = Buffer.add_char string_buffer c
      method store_string_utf_8_uchar u = Buffer.add_utf_8_uchar string_buffer u
      method store_string s = Buffer.add_string string_buffer s

      method store_substring s ~pos ~len =
        Buffer.add_substring string_buffer s pos len

      method store_lexeme lexbuf = self#store_string (Lexing.lexeme lexbuf)

      method store_normalized_newline newline =
        (* OCamlformat: We preserve the line endings in string literals. *)
        self#store_string newline
    end

let foo = fun -> "a"
  let code_buffer = new lexeme_buffer
  let results : result list ref = ref []
  let add_result s = results := s :: !results
}

let blanks = [' ' '\t']*

let linenum_directive =
  '#' blanks (['0'-'9']+ as line) blanks '"' ([^'"']+ as text) '"' blanks '\n'

rule read_line_directives = parse
| linenum_directive
  {
    Lexing.new_line lexbuf;
    log "read opening linenum_directive: # %d %s" (int_of_string line) text;
    let src_line = int_of_string line in
    read_code (Lexing.lexeme_end_p lexbuf) src_line lexbuf
  }
| eof { () }
| _ as c
  {
    if c = '\n' then Lexing.new_line lexbuf;
    read_line_directives lexbuf
  }

and read_code startpos src_line = parse
| linenum_directive
  {
    Lexing.new_line lexbuf;
    let endpos = Lexing.lexeme_start_p lexbuf in
    let impl_line = int_of_string line in
    log "read closing linenum_directive: # %s %s" line text;
    let range = (startpos, endpos) in
    let text = code_buffer#get_stored_string () in
    log "code: %a |%s|" Range.pp_lexing range text;
    add_result { impl_line; src_line; range; text };
    (* Search for other directives in the rest of the input *)
    code_buffer#reset_string_buffer ();
    read_line_directives lexbuf
  }
| eof { failwith "Unterminated code section" }
| _ as c
  {
    if c = '\n' then Lexing.new_line lexbuf;
    code_buffer#store_string_char c;
    read_code startpos src_line lexbuf
  }
