(library
 (name test_debug)
 (libraries menhirLib linkage menhirdebug_lib))

(ocamllex calc_lexer)

(menhir
 (modules calc)
 (flags --table --inspection))

(rule
 (targets calc_debug.cmxs)
 (action
  (run
   %{ocamlopt}
   -shared
   -o
   %{targets}
   %{cmx:calc}
   %{cmx:calc_debug}
   -I
   /home/dalpi/.opam/5.4.0/lib/menhirLib)))
