set allow-duplicate-recipes := true

entrypoints := "src/extension.ts src/test/*.ts"
common_opts := "--format=cjs --platform=node --bundle --external:vscode --external:mocha --external:'@vscode/test-electron' --outdir='out'"

default: build

build:
    esbuild {{ entrypoints }} {{ common_opts }} --sourcemap

build-webviews:
    node src/webviews/build.ts

# [working-directory: '..']
# install:
#     dune install --build-info

test: build
    node out/test/runTest.js

watch:
    esbuild {{ entrypoints }} {{ common_opts }} --sourcemap --watch

bundle:
    esbuild {{ entrypoints }} {{ common_opts }} --minify

package version:
    vsce pack {{ version }} -o vsix/

publish:
    vsce publish
